"""Add Collections, AlertRules, and SavedFilterPresets tables

Revision ID: 2887a43d7aef
Revises: e10338a3480e
Create Date: 2026-03-17 17:40:08.703710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2887a43d7aef'
down_revision: Union[str, Sequence[str], None] = 'e10338a3480e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('condition', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index('ix_alert_rules_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index('ix_alert_rules_user_id', ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_ids_json', sa.Text(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('share_slug', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_slug')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('ix_collections_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_collections_votes', ['votes'], unique=False)

    op.create_table('saved_filter_presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filter_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_filter_presets', schema=None) as batch_op:
        batch_op.create_index('ix_saved_filter_presets_user_id', ['user_id'], unique=False)

    op.create_table('collection_votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id', name='uq_collection_vote')
    )
    with op.batch_alter_table('collection_votes', schema=None) as batch_op:
        batch_op.create_index('ix_collection_votes_collection_id', ['collection_id'], unique=False)

    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    if not inspector.has_table('alert_notifications'):
        op.create_table('alert_notifications',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('alert_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=128), nullable=True),
        sa.Column('destination_email', sa.String(length=255), nullable=False),
        sa.Column('channel', sa.String(length=24), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['alert_id'], ['trend_alerts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('alert_id', 'destination_email', 'channel', name='uq_alert_notification_delivery')
        )
        with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_alert_notifications_alert_id'), ['alert_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_alert_notifications_destination_email'), ['destination_email'], unique=False)
            batch_op.create_index(batch_op.f('ix_alert_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_api_keys_hash'))
        batch_op.drop_constraint(batch_op.f('uq_api_keys_hash'), type_='unique')
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    with op.batch_alter_table('category_metrics_daily', schema=None) as batch_op:
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_contributors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_merged_prs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('repo_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_star_gain',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_pr_gain',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('avg_open_prs',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weekly_velocity',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mom_growth_pct',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('trend_composite',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('ecosystem_reports', schema=None) as batch_op:
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_er_generated_at'))
        batch_op.drop_index(batch_op.f('ix_er_period_type'))
        batch_op.create_index(batch_op.f('ix_ecosystem_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_reports_period_type'), ['period_type'], unique=False)

    with op.batch_alter_table('fork_snapshots', schema=None) as batch_op:
        batch_op.alter_column('captured_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_fs_parent_repo_id'))
        batch_op.drop_index(batch_op.f('ix_fs_snapshot_date'))
        batch_op.create_index(batch_op.f('ix_fork_snapshots_parent_repo_id'), ['parent_repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fork_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    with op.batch_alter_table('repo_contributors', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_rc_login'))
        batch_op.drop_index(batch_op.f('ix_rc_repo_id'))
        batch_op.create_index(batch_op.f('ix_repo_contributors_login'), ['login'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_contributors_repo_id'), ['repo_id'], unique=False)

    with op.batch_alter_table('repo_releases', schema=None) as batch_op:
        batch_op.alter_column('is_prerelease',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('social_mentions', schema=None) as batch_op:
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.alter_column('is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_subscribers_confirm_token'))
        batch_op.drop_index(batch_op.f('ix_subscribers_unsub_token'))

    with op.batch_alter_table('trend_alerts', schema=None) as batch_op:
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_watchlist_repo_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.create_index(batch_op.f('ix_watchlist_items_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_repo_id'))
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_repo_id'), ['repo_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('trend_alerts', schema=None) as batch_op:
        batch_op.alter_column('threshold',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_unsub_token'), ['unsubscribe_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_confirm_token'), ['confirm_token'], unique=False)
        batch_op.alter_column('is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('social_mentions', schema=None) as batch_op:
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('repo_releases', schema=None) as batch_op:
        batch_op.alter_column('is_prerelease',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('repo_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_contributors_repo_id'))
        batch_op.drop_index(batch_op.f('ix_repo_contributors_login'))
        batch_op.create_index(batch_op.f('ix_rc_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rc_login'), ['login'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('fork_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fork_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_fork_snapshots_parent_repo_id'))
        batch_op.create_index(batch_op.f('ix_fs_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fs_parent_repo_id'), ['parent_repo_id'], unique=False)
        batch_op.alter_column('captured_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ecosystem_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_reports_period_type'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_reports_generated_at'))
        batch_op.create_index(batch_op.f('ix_er_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_er_generated_at'), ['generated_at'], unique=False)
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('category_metrics_daily', schema=None) as batch_op:
        batch_op.alter_column('trend_composite',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mom_growth_pct',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weekly_velocity',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('avg_open_prs',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_pr_gain',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_star_gain',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('repo_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_merged_prs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_contributors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.create_unique_constraint(batch_op.f('uq_api_keys_hash'), ['key_hash'])
        batch_op.create_index(batch_op.f('ix_api_keys_hash'), ['key_hash'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('alert_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_notifications_destination_email'))
        batch_op.drop_index(batch_op.f('ix_alert_notifications_alert_id'))

    op.drop_table('alert_notifications')
    with op.batch_alter_table('collection_votes', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_votes_collection_id')

    op.drop_table('collection_votes')
    with op.batch_alter_table('saved_filter_presets', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_filter_presets_user_id')

    op.drop_table('saved_filter_presets')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('ix_collections_votes')
        batch_op.drop_index('ix_collections_created_by')

    op.drop_table('collections')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_rules_user_id')
        batch_op.drop_index(batch_op.f('ix_alert_rules_repo_id'))
        batch_op.drop_index('ix_alert_rules_active')

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
