"""initial_schema

Revision ID: 8feacc6313a1
Revises: 
Create Date: 2026-03-03 23:44:12.543424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feacc6313a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=False),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_category'), 'repositories', ['category'], unique=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('computed_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('star_velocity_7d', sa.Float(), nullable=True),
    sa.Column('star_velocity_30d', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('contributor_growth_rate', sa.Float(), nullable=True),
    sa.Column('fork_to_star_ratio', sa.Float(), nullable=True),
    sa.Column('issue_close_rate', sa.Float(), nullable=True),
    sa.Column('release_frequency', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('sustainability_score', sa.Float(), nullable=True),
    sa.Column('sustainability_label', sa.String(length=10), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_metrics_date'), 'computed_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_computed_metrics_repo_id'), 'computed_metrics', ['repo_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('contributors', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('merged_prs', sa.Integer(), nullable=True),
    sa.Column('releases', sa.Integer(), nullable=True),
    sa.Column('daily_star_delta', sa.Integer(), nullable=True),
    sa.Column('daily_fork_delta', sa.Integer(), nullable=True),
    sa.Column('language_breakdown', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_metrics_captured_at'), 'daily_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_daily_metrics_repo_id'), 'daily_metrics', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_metrics_repo_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_captured_at'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_computed_metrics_repo_id'), table_name='computed_metrics')
    op.drop_index(op.f('ix_computed_metrics_date'), table_name='computed_metrics')
    op.drop_table('computed_metrics')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_category'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
