"""Add index for trend score and sustainability

Revision ID: a6b1c6f58761
Revises: 2887a43d7aef
Create Date: 2026-03-28 10:13:18.586014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b1c6f58761'
down_revision: Union[str, Sequence[str], None] = '2887a43d7aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_messages_session_id'))

    op.drop_table('research_messages')
    with op.batch_alter_table('research_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_shares_session_id'))
        batch_op.drop_index(batch_op.f('ix_research_shares_token'))

    op.drop_table('research_shares')
    with op.batch_alter_table('research_pins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_pins_session_id'))
        batch_op.drop_index(batch_op.f('ix_research_pins_session_repo'))

    op.drop_table('research_pins')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_user_updated'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_reports_session_id'))

    op.drop_table('research_reports')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_api_keys_hash'))
        batch_op.drop_constraint(batch_op.f('uq_api_keys_hash'), type_='unique')
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    with op.batch_alter_table('category_metrics_daily', schema=None) as batch_op:
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_contributors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_merged_prs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('repo_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_star_gain',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_pr_gain',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('avg_open_prs',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weekly_velocity',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mom_growth_pct',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('trend_composite',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('computed_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_computed_metrics_date_sust', ['date', 'sustainability_score'], unique=False)
        batch_op.create_index('ix_computed_metrics_date_trend', ['date', 'trend_score'], unique=False)

    with op.batch_alter_table('ecosystem_reports', schema=None) as batch_op:
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_er_generated_at'))
        batch_op.drop_index(batch_op.f('ix_er_period_type'))
        batch_op.create_index(batch_op.f('ix_ecosystem_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecosystem_reports_period_type'), ['period_type'], unique=False)

    with op.batch_alter_table('fork_snapshots', schema=None) as batch_op:
        batch_op.alter_column('captured_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_fs_parent_repo_id'))
        batch_op.drop_index(batch_op.f('ix_fs_snapshot_date'))
        batch_op.create_index(batch_op.f('ix_fork_snapshots_parent_repo_id'), ['parent_repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fork_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    with op.batch_alter_table('repo_contributors', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_rc_login'))
        batch_op.drop_index(batch_op.f('ix_rc_repo_id'))
        batch_op.create_index(batch_op.f('ix_repo_contributors_login'), ['login'], unique=False)
        batch_op.create_index(batch_op.f('ix_repo_contributors_repo_id'), ['repo_id'], unique=False)

    with op.batch_alter_table('repo_releases', schema=None) as batch_op:
        batch_op.alter_column('is_prerelease',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('social_mentions', schema=None) as batch_op:
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.alter_column('is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_subscribers_confirm_token'))
        batch_op.drop_index(batch_op.f('ix_subscribers_unsub_token'))

    with op.batch_alter_table('trend_alerts', schema=None) as batch_op:
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('threshold',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_watchlist_repo_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.create_index(batch_op.f('ix_watchlist_items_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_repo_id'))
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_repo_id'), ['repo_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('trend_alerts', schema=None) as batch_op:
        batch_op.alter_column('threshold',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('metric_value',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_unsub_token'), ['unsubscribe_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_confirm_token'), ['confirm_token'], unique=False)
        batch_op.alter_column('is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('social_mentions', schema=None) as batch_op:
        batch_op.alter_column('comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('repo_releases', schema=None) as batch_op:
        batch_op.alter_column('is_prerelease',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('repo_contributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repo_contributors_repo_id'))
        batch_op.drop_index(batch_op.f('ix_repo_contributors_login'))
        batch_op.create_index(batch_op.f('ix_rc_repo_id'), ['repo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rc_login'), ['login'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('fork_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fork_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_fork_snapshots_parent_repo_id'))
        batch_op.create_index(batch_op.f('ix_fs_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fs_parent_repo_id'), ['parent_repo_id'], unique=False)
        batch_op.alter_column('captured_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ecosystem_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecosystem_reports_period_type'))
        batch_op.drop_index(batch_op.f('ix_ecosystem_reports_generated_at'))
        batch_op.create_index(batch_op.f('ix_er_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_er_generated_at'), ['generated_at'], unique=False)
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('computed_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_computed_metrics_date_trend')
        batch_op.drop_index('ix_computed_metrics_date_sust')

    with op.batch_alter_table('category_metrics_daily', schema=None) as batch_op:
        batch_op.alter_column('trend_composite',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mom_growth_pct',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('weekly_velocity',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('avg_open_prs',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_pr_gain',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('period_star_gain',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('repo_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_merged_prs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_contributors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.create_unique_constraint(batch_op.f('uq_api_keys_hash'), ['key_hash'])
        batch_op.create_index(batch_op.f('ix_api_keys_hash'), ['key_hash'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.create_table('research_reports',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content_md', sa.TEXT(), nullable=False),
    sa.Column('repos_count', sa.INTEGER(), nullable=False),
    sa.Column('queries_json', sa.TEXT(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_reports_session_id'), ['session_id'], unique=1)

    op.create_table('research_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('verticals_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_user_updated'), ['user_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_created_at'), ['created_at'], unique=False)

    op.create_table('research_pins',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('repo_full_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('repo_data_json', sa.TEXT(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('stage', sa.VARCHAR(length=20), nullable=False),
    sa.Column('pinned_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_pins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_pins_session_repo'), ['session_id', 'repo_full_name'], unique=1)
        batch_op.create_index(batch_op.f('ix_research_pins_session_id'), ['session_id'], unique=False)

    op.create_table('research_shares',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_shares_token'), ['token'], unique=1)
        batch_op.create_index(batch_op.f('ix_research_shares_session_id'), ['session_id'], unique=1)

    op.create_table('research_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('intent', sa.VARCHAR(length=30), nullable=True),
    sa.Column('github_query', sa.TEXT(), nullable=True),
    sa.Column('query_explanation', sa.TEXT(), nullable=True),
    sa.Column('repos_json', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
