"""Add missing db indexes for performance

Revision ID: e10338a3480e
Revises: h8i9j0k1l2m
Create Date: 2026-03-17 09:40:04.525991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10338a3480e'
down_revision: Union[str, Sequence[str], None] = 'h8i9j0k1l2m'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('computed_metrics', 'computed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('computed_metrics', 'star_velocity_7d',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'star_velocity_30d',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'acceleration',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'contributor_growth_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'fork_to_star_ratio',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'issue_close_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'release_frequency',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'trend_score',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'sustainability_score',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('computed_metrics', 'sustainability_label',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_index('ix_computed_metrics_repo_date', 'computed_metrics', ['repo_id', 'date'], unique=False)
    op.alter_column('daily_metrics', 'stars',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'forks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'watchers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'contributors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'open_issues',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'open_prs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('daily_metrics', 'merged_prs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'releases',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'daily_star_delta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'daily_fork_delta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'daily_pr_delta',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index('ix_daily_metrics_repo_date', 'daily_metrics', ['repo_id', 'captured_at'], unique=False)
    op.alter_column('repositories', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('repositories', 'age_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_repositories_is_active'), 'repositories', ['is_active'], unique=False)
    op.create_index('ix_repositories_owner_name', 'repositories', ['owner', 'name'], unique=False)
    op.create_index('ix_repositories_source_active', 'repositories', ['source', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_repositories_source_active', table_name='repositories')
    op.drop_index('ix_repositories_owner_name', table_name='repositories')
    op.drop_index(op.f('ix_repositories_is_active'), table_name='repositories')
    op.alter_column('repositories', 'age_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('ix_daily_metrics_repo_date', table_name='daily_metrics')
    op.alter_column('daily_metrics', 'daily_pr_delta',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('daily_metrics', 'daily_fork_delta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'daily_star_delta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'releases',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'merged_prs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'open_prs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('daily_metrics', 'open_issues',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'contributors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'watchers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'forks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'stars',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_computed_metrics_repo_date', table_name='computed_metrics')
    op.alter_column('computed_metrics', 'sustainability_label',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('computed_metrics', 'sustainability_score',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'trend_score',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'release_frequency',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'issue_close_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'fork_to_star_ratio',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'contributor_growth_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'acceleration',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'star_velocity_30d',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'star_velocity_7d',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('computed_metrics', 'computed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
